if(NOT EXISTS "${RUNFLOW_BOOST_ROOT}/boost/version.hpp")
  message(FATAL_ERROR "Pinned Boost headers required")
endif()
file(READ "${RUNFLOW_BOOST_ROOT}/boost/version.hpp" _boost_version_header)
if(NOT _boost_version_header MATCHES "#define BOOST_VERSION 108700")
  message(FATAL_ERROR "Boost 1.87.0 required")
endif()
set(Boost_FOUND TRUE)
set(Boost_VERSION "1.87.0")
set(Boost_INCLUDE_DIRS "${RUNFLOW_BOOST_ROOT}")
set(Boost_LIBRARIES "")
if(NOT TARGET Boost::boost)
  add_library(Boost::boost INTERFACE IMPORTED)
  set_target_properties(Boost::boost PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${RUNFLOW_BOOST_ROOT}")
endif()
